In [21]:
import yfinance as yf
import numpy as np
import pandas as pd

df = yf.download("GBPUSD=X", start="2000-01-01", auto_adjust=True, interval = "1h")
returns = np.log(df["Close"] / df["Close"].shift(1)).dropna()

print(f"Mean abs daily return: {returns.abs().mean()}")
print(f"Std of daily returns:  {returns.std()}")
print(f"25th percentile abs:   {returns.abs().quantile(0.25)}")
print(f"75th percentile abs:   {returns.abs().quantile(0.75)}")

$GBPUSD=X: possibly delisted; no price data found  (1h 2000-01-01 -> 2026-06-28 11:18:08+01:00) (Yahoo error = "1h data not available for startTime=1070236800 and endTime=1782641888. The requested range must be within the last 730 days.")
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['GBPUSD=X']: possibly delisted; no price data found  (1h 2000-01-01 -> 2026-06-28 11:18:08+01:00) (Yahoo error = "1h data not available for startTime=1070236800 and endTime=1782641888. The requested range must be within the last 730 days.")

Mean abs daily return: Ticker
GBPUSD=X   NaN
dtype: float64
Std of daily returns:  Ticker
GBPUSD=X   NaN
dtype: float64
25th percentile abs:   Ticker
GBPUSD=X   NaN
Name: 0.25, dtype: float64
75th percentile abs:   Ticker
GBPUSD=X   NaN
Name: 0.75, dtype: float64

In [34]:
from datetime import datetime, timedelta
import pandas as pd



import sys
import os

from yfinance import ticker
#sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import logging
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import yfinance as yf
import yaml

def fetch_ohlcv(ticker: str, start: str, end: str | None, interval: str = "1d") -> pd.DataFrame:
    """Download daily OHLCV from yfinance."""
    #log.info(f"Downloading {ticker} from {start} to {end or 'today'}")
    end = end or datetime.today().strftime("%Y-%m-%d")
    
    df = yf.download(ticker, start=start, end=end, auto_adjust=True, progress=False, interval=interval)

    if df.empty:
        raise ValueError(f"No data returned for ticker '{ticker}'. Check your internet connection.")
    print(df.head())
    # yfinance returns MultiIndex columns when downloading single ticker in newer versions
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.droplevel(1)

    df = df[["Open", "High", "Low", "Close", "Volume"]].copy()
    df.columns = ["open", "high", "low", "close", "volume"]
    df.index.name = "date"
    df = df.sort_index()
    return df

    #log.info(f"Fetched {len(df)} rows  |  {df.index[0].date()} → {df.index[-1].date()}")

In [35]:
df = fetch_ohlcv("GBPUSD=X", "2000-01-01", None, "1d")

Price          Close      High       Low      Open   Volume
Ticker      GBPUSD=X  GBPUSD=X  GBPUSD=X  GBPUSD=X GBPUSD=X
Date
2003-12-01  1.718597  1.727205  1.718390  1.723811        0
2003-12-02  1.730313  1.732112  1.717298  1.719010        0
2003-12-03  1.728101  1.731812  1.725209  1.730493        0
2003-12-04  1.720697  1.728997  1.718302  1.727414        0
2003-12-05  1.733102  1.733102  1.719809  1.720608        0

In [37]:
df.tail()

                open      high       low     close  volume
date
2026-06-22  1.320830  1.327211  1.318513  1.320795       0
2026-06-23  1.324644  1.325030  1.318635  1.324714       0
2026-06-24  1.320080  1.320934  1.314302  1.320010       0
2026-06-25  1.316274  1.321702  1.315322  1.316656       0
2026-06-26  1.319662  1.323014  1.318113  1.319801       0

In [12]:
from pathlib import Path
ticker = "GBPUSD=X"
raw_path= r"data/fetch/raw.parquet"
processed_path= r"data/fetch/processed.parquet"

raw_path = Path(raw_path).with_name(f"{ticker.lower().split('=')[0]}_raw.parquet")
proc_path = Path(processed_path).with_name(f"{ticker.lower().split('=')[0]}_processed.parquet")

In [11]:
print(f"Raw path: {raw_path}")

Raw path: data\fetch\gbpusd.parquet

In [2]:
df = pd.read_csv(r"C:\Users\Agaba_Embedded4\Desktop\Price prediction-end-to-end\data\features\featured_eurusd.csv")

In [16]:
a  = Path("akdjeieiei") / f"jdieeje/feature_columns.json"
a

WindowsPath('akdjeieiei/jdieeje/feature_columns.json')

In [ ]:
ac

In [3]:
df.columns

Index(['open', 'high', 'low', 'close', 'volume', 'log_return',
       'next_log_return', 'label', 'body', 'body_abs',
       ...
       'ret_min_30d', 'ret_max_30d', 'pos_days_30d', 'ret_mean_63d',
       'ret_std_63d', 'ret_skew_63d', 'ret_kurt_63d', 'ret_min_63d',
       'ret_max_63d', 'pos_days_63d'],
      dtype='object', length=137)

In [4]:
df["label"]

0      1
1      1
2      1
3      1
4      3
      ..
420    1
421    1
422    1
423    0
424    2
Name: label, Length: 425, dtype: int64

In [11]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
df = pd.read_csv("test_predictions_RandomForest.csv")
df = df[df["predicted"] != 2]
#df_dir = df.copy()
df['dir_actual']= df["actual"].apply(lambda x: 1 if x == 3 or x == 4 else (0 if x == 0 or x == 1 else -1))
df['dir_pred']= df["predicted"].apply(lambda x: 1 if x == 3 or x == 4 else (0 if x == 0 or x == 1 else -1))

In [13]:
df.tail(100)

           date  actual  predicted  dir_actual  dir_pred
693  2025-11-24       2          3          -1         1
694  2025-11-25       3          3           1         1
697  2025-11-28       2          1          -1         0
698  2025-12-01       2          3          -1         1
700  2025-12-03       3          3           1         1
..          ...     ...        ...         ...       ...
843  2026-06-24       1          1           0         0
845  2026-06-26       3          3           1         1
846  2026-06-29       3          3           1         1
847  2026-06-30       2          1          -1         0
848  2026-07-01       1          1           0         0

[100 rows x 5 columns]

In [116]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
df = pd.read_csv("test_predictions_RandomForest.csv")
df = df[df["predicted"] != 2]
#df_dir = df.copy()
df['dir_actual']= df["actual"].apply(lambda x: 1 if x == 3 or x == 4 else (0 if x == 0 or x == 1 else -1))
df['dir_pred']= df["predicted"].apply(lambda x: 1 if x == 3 or x == 4 else (0 if x == 0 or x == 1 else -1))
df2 = pd.read_parquet(r"C:\Users\Agaba_Embedded4\Desktop\Price prediction-end-to-end\data\fetch\eurusd_raw.parquet")
df2["shifted"] = df2["close"].shift(-1)
df2 = df2.ffill()
df2["dir"] = df2.apply(lambda x: 1 if x["shifted"] > x["close"] else (0 if x["shifted"] < x["close"] else 0), axis=1)
# Create a mask for the rows you want to target
mask = df["dir_actual"] == -1

# Use .loc[row_indexer, column_indexer]
df.loc[mask, "dir_actual"] = df2.loc[df.loc[mask, "date"], "dir"].values

accuracy = accuracy_score(df["dir_actual"], df["dir_pred"])

f1_score = f1_score(df["dir_actual"], df["dir_pred"])#, average='weighted')

In [117]:
print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1_score}")

Accuracy: 0.8723747980613893
F1 Score: 0.8581687612208259

In [112]:
df = df[df["dir_actual"] != -1]

In [113]:
f1_score(df["dir_actual"], df["dir_pred"], average='macro')

0.9534228566062541

In [114]:
accuracy_score(df["dir_actual"], df["dir_pred"])

0.9536290322580645

In [115]:
len(df)

496

In [102]:
df2 = pd.read_parquet(r"C:\Users\Agaba_Embedded4\Desktop\Price prediction-end-to-end\data\fetch\eurusd_raw.parquet")
df2["shifted"] = df2["close"].shift(-1)
df2 = df2.ffill()
df2["dir"] = df2.apply(lambda x: 1 if x["shifted"] > x["close"] else (0 if x["shifted"] < x["close"] else 0), axis=1)
# Create a mask for the rows you want to target
mask = df["dir_actual"] == -1

# Use .loc[row_indexer, column_indexer]
df.loc[mask, "dir_actual"] = df2.loc[df.loc[mask, "date"], "dir"].values

In [103]:
accuracy_score(df["dir_actual"], df["dir_pred"])

0.8723747980613893

In [104]:
f1_score(df["dir_actual"], df["dir_pred"])#, average='weighted')

0.8581687612208259

In [119]:
df = pd.read_csv(r"C:\Users\Agaba_Embedded4\Desktop\Price prediction-end-to-end\data\features\eurusd\features.csv")

In [120]:
df.head()

,open,high,low,close,volume,log_return,next_log_return,label,body,body_abs,...,ret_min_30d,ret_max_30d,pos_days_30d,ret_mean_63d,ret_std_63d,ret_skew_63d,ret_kurt_63d,ret_min_63d,ret_max_63d,pos_days_63d
0,1.203398,1.204007,1.194401,1.196501,0,NaN,0.010307,1,-0.006897,0.006897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.196101,1.210903,1.194600,1.208897,0,0.010307,0.002809,1,0.012797,0.012797,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.209000,1.213003,1.207700,1.212298,0,0.002809,-0.003473,0,0.003298,0.003298,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.212004,1.214403,1.204398,1.208094,0,-0.003473,0.008736,1,-0.003909,0.003909,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.207802,1.219096,1.206593,1.218695,0,0.008736,0.002709,1,0.010892,0.010892,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN